[SWDEV-138]Welcome to the stage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,3 +44,15 @@ jobs:
               docker tag $DOCKER_NAME:$BRANCH_NAME 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-midway:$TAG
               docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-midway:$TAG
             done
+
+            kops export kubecfg --name ${K8S_CLUSTER}.k8s.ankr.network --state s3://kops.${K8S_CLUSTER}.config
+            mkdir ./k8s/tmp
+
+            kubectl patch --local -o yaml -p \
+            '{"spec":{"template":{"spec":{"containers":[{"name":"midway","image":"'${AWS_ACCOUNT}'.dkr.ecr.'${AWS_REGION}'.amazonaws.com/dccn-midway:'${BRANCH_NAME}''${DATE}'"}]}}}}' \
+            -f ./k8s/dccn-midway.yml > ./k8s/tmp/dccn-midway.yml
+            kubectl apply -f ./kubernetes/tmp/dccn-midway.yml
+            if ! kubectl rollout status deploy/midway --watch=true --timeout=60s; then
+              echo "Deploy failed, roll back to previous version"
+              kubectl rollout undo deploy/midway
+            fi
